---
- name: Listen for Webhook and Launch Controller Job
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5000

  rules:
    - name: Trigger Job Template on specific payload
      #condition: event.payload.status == "critical"
      action:
        run_job_template:
          name: "Demo Job Template" # The name of your AAP Job Template
          organization: "Default"
